### ISSUE TITLE
Not working with react-tap-event-plugin

### ISSUE THREAD

**Issue by mlarcher** [milankinen/livereactload#104]
When using `injectTapEventPlugin();` from the `react-tap-event-plugin` module, I get the following error in the Chrome console when using livereactload :
`Uncaught TypeError: keyOf is not a function`
This is not happening when livereactload is not plugged.

This plugin is required by the material-ui Datepicker.
Here's a minimal testcase: 
[sample-app2.zip](https://github.com/milankinen/livereactload/files/148219/sample-app2.zip)

I hope you can figure it out as fast as the previous one ;)

**Comment by milankinen** [comment]
Damn. Ok have to check if version `2.2.0` broke something...

**Comment by mlarcher** [comment]
Any news on the matter by any chance ? Is there anything I can do to help you on that ?

**Comment by milankinen** [comment]
It's the damn dedupe handling again. Your example was great again, I found the bug... not just figured out how to solve it..

**Comment by mlarcher** [comment]
any news on the matter @milankinen ?

**Comment by milankinen** [comment]
I added `--no-dedupe` option (`{dedupe: false}`) in [`2.2.3`](https://github.com/milankinen/livereactload/releases/tag/2.2.3) which disables Browserify's de-duplication pipeline stage.

That's not the final solution but should fix this issue. If duplicated modules are stateful, the using `--no-dedupe` might cause some troubles. Otherwise its usage should be harmless.

**Comment by luckyraul** [comment]
https://github.com/rofrischmann/inline-style-prefixer/issues/85
I got the same feeling about my problem.

**Comment by milankinen** [comment]
@luckyraul does `--no-dedupe` option help?

**Comment by luckyraul** [comment]
@milankinen  no

**Comment by milankinen** [comment]
Fixed in `3.0.0`.
