### ISSUE TITLE
Third-party questions

### ISSUE THREAD

**Issue by neemzy** [milankinen/livereactload#129]
Hi there!

I'd like to ask a few questions about required third-party libs:
- `babel-plugin-react-transform` seems to be [deprecated](https://github.com/gaearon/babel-plugin-react-transform#this-project-is-deprecated), and I was wondering whether it would be possible to just switch to [`babel-plugin-transform-react-jsx`](https://www.npmjs.com/package/babel-plugin-transform-react-jsx), which is part of Babel itself?
- Why aren't `watchify`, `babelify`, `babel-preset-es2015` (or even better, [`babel-preset-latest`](https://babeljs.io/docs/plugins/preset-latest/)), `babel-preset-react` and `react-proxy@1.x` dependencies of this project, which would prevent you from having to tell your users to install them manually?

Maybe these are silly questions, sorry if they've already been answered elsewhere (I've looked around but may have missed it). Thanks!

**Comment by milankinen** [comment]
Hi @neemzy, and thanks for your questions!

>`babel-plugin-react-transform` seems to be deprecated, and I was wondering whether it would be possible to just switch to `babel-plugin-transform-react-jsx`, which is part of Babel itself?

Hmmm, interesting. Does `babel-plugin-transform-react-jsx` support some kind of post-decoration that is needed for livereloading? If that's possible, I'd gladly use "official" packages instead of "unofficial" (athough de facto) ones.

> Why aren't watchify, babelify, babel-preset-es2015 (or even better, babel-preset-latest), babel-preset-react and react-proxy@1.x dependencies of this project, which would prevent you from having to tell your users to install them manually?

Since LiveReactload is a Browserify plugin, I want to respect the ideology of Browserify: you can build your environment from small independent building blocks, instead of having a configurable monolith (like Webpack). Enforcing external dependencies (like specific Babel preset) is (at least IMHO) against that goal. That's why I'm a bit reluctant to lock into specific external packages.

However, I'd happily welcome some new package that combines `watchify`, `livereactload`, `babelify` et al. into single package, in a spirit of `create-react-app` (and perhaps with `eject` feature). 😄

**Comment by neemzy** [comment]
Hi @milankinen, thanks for your thorough answer as always :)

I looked through the `babel-plugin-transform-react-jsx` source but honestly couldn't tell. What should I be looking for? I'm not sure what you mean by post-decoration. Maybe @gaearon could be of any help? What would you advise regarding the deprecation of `babel-plugin-react-transform`?

You have a point regarding my other question, I understand that. Thanks!

**Comment by milankinen** [comment]
@neemzy Can we close this issue?

**Comment by neemzy** [comment]
Sure!
