### ISSUE TITLE
[Question] Is there a way to deal with global events being duplicated?

### ISSUE THREAD

**Issue by josh18** [milankinen/livereactload#52]
For example if I do something like:
```js
document.addEventListener('click', function() {
    console.log('click');
});
```
I get an extra event running every time the javascript is reloaded.

**Comment by milankinen** [comment]
Are you adding your event listener inside the react component or on the "top" of your application?

**Comment by josh18** [comment]
Originally I was adding it outside react but I thought this might be the issue so I also tried it inside a react component but it seems to have the same result. I was doing something like:
```js
componentWillMount: function() {
    document.addEventListener('click', function() {
        console.log('click');
    });
},
```
(I'm still learning react so I might be doing something wrong.)

**Comment by josh18** [comment]
Is this a bug, intentional, or am I doing something wrong?

**Comment by milankinen** [comment]
Generally it's good practice in React to place such listeners inside the component's `componentDidMount` method and remove the listener in `componentWillUnmount` e.g.

```javascript
export default class MyComponent extends React.Component {
  doSomething() {
   ...
  } 
  componentDidMount() {
    document.addEventListener("click", this.doSomething.bind(this))
  }
  componentWillUnmount() {
    document.removeEventListener("click", this.doSomething)
  }
  ...
}
```
If you are interested events only "generally", then you can bind the listeners inside your root component's `componentDidMount` and ignore the removing code (because your root element will never unmount).

**Comment by josh18** [comment]
Ok that makes sense, thanks!
