### ISSUE TITLE
info required

### ISSUE THREAD

**Issue by ORESoftware** [milankinen/livereactload#58]
hello authors:

this is a request for information -
I wrote this article on hot-reloading React components with RequireJS. My main goal is to show that hot-reloading is easiest when using RequireJS instead of Browserify or Webpack, but I would like to do Browserify and Webpack justice. If you have time to read this and offer any feedback you can email me at alex@oresoftware.com, thanks for your help -

https://medium.com/@the1mills/hot-reloading-with-react-requirejs-7b2aa6cb06e1

**Comment by milankinen** [comment]
@ORESoftware I'd like to comment your solution but first I need to check it. I tried to clone your example project but it is way too complex for "testing/PoCing" purposes. I'd advice you to simplify your example project so that it contains only the "beef", thus lowering the level of people to test it.

However, I finally managed to get your example up and running and found the correct files to modify (this was the hardest part). There are at least two flaws in your "hot reloading":

* If I type something to the "First name" field and then modify login template, all typed text disappear (same goes for any other forms, e.g. user profile)
* `FluxCart` is not working (blank page only) so that I could test flux reloading

**Comment by ORESoftware** [comment]
thanks, I will definitely simplify the project, thats a good idea.

as for the typed text - at the moment there is nothing in the app that
stores the typed text - so the state before the typing is exactly the same
as the state after typing - this is why when you reload the template the
text is gone. if we use some two way binding, then we can store the text
and in that case the text would "reappear" when the template was reloaded.

I will simplify the code and let you know when it's done, probably later
today

**Comment by milankinen** [comment]
Thanks, I'll look forward the simplified example.

But you can't say that your approach is closer to "universal hot-reloading" if the DOM state is wiped away every reload. ;-)

**Comment by ORESoftware** [comment]
hmmm, I don't follow - the DOM state isn't storing the text, is it? ...I haven't been in web development long enough to know that much about that,  but I do know this -

think about it - you edit templates or React views on the fly, the same field that you are typing into might change altogether, so it's better to wipe the DOM state anyway, makes sense? :) no state should be stored in the DOM anyhow, that's a good philosophy.

there are a couple limitations to my design, one of them being that I don't know which view the developer is editing, so the best I can do is just re-render the current view on the screen, which is usually good enough.

**Comment by ORESoftware** [comment]
I do agree that it would be useful to the developer to have the text or DOM state re-used after a hot-reload, however, the proper way to do that would be to store the DOM state in models/stores, using 2-way binding.

**Comment by ORESoftware** [comment]
the FluxActions and FluxConstants will be "hot-reloadable" but I am still working to finish that part; if you don't mind I could ping you in a week or two when that's done, if you could help me test the example product, that would be really cool, I can also offer my help to test out your lib, although it looks like you have plenty of users/feedback already :)

**Comment by milankinen** [comment]
Closing this one
