### ISSUE TITLE
Fails with latest react-proxy (2.0.0)

### ISSUE THREAD

**Issue by deelan** [milankinen/livereactload#72]
I get "Uncaught TypeError: getForceUpdate is not a function" in the browser when loading my app. I recently updated to react 0.14 and the latest redux-react (4.0.0)

The latest react-proxy which now supports react 0.14 removed the getForceUpdate function (among other things).

The only way I can run my app is to disable livereactload. Please update to work with latest react-proxy ASAP.

Thanks!

**Comment by gaearon** [comment]
React Proxy 2.0 has important breaking changes.
Until LiveReactload supports them, you should stick with 1.x.

**Comment by dylanmerrick** [comment]
Ok, I'll downgrade react-proxy for now. Thanks.

**Comment by milankinen** [comment]
As @gaearon said, `npm i --save-dev react-proxy@1.x` will do the job for now.

Need to investigate more about this issue before I can apply `react-proxy@2.x` to livereactload

**Comment by DerFlatulator** [comment]
Any updates on this issue?

**Comment by milankinen** [comment]
Nope. :disappointed: `react-proxy@2.x` has so many differences compared to the original `1.x` so that migration would be pain. :cry: 

If someone is interested to help, `2.x` support would require a total re-write of [this file](https://github.com/milankinen/livereactload/blob/master/src/babel-transform/main.js). PR's welcome! :smile:

**Comment by milankinen** [comment]
`react-proxy` seems to use `1.x` as a default branch so I'll close this one until `2.x` becomes more popular.
