### ISSUE TITLE
Change detected but update not applied

### ISSUE THREAD

**Issue by aaronpowell** [milankinen/livereactload#79]
I'm playing around with this plugin and combining it with a TypeScript + React project (rather than Babel as the transpiler).

I've got lrload plugged in as per the docs but it's not working as expected, what I'm finding is:

* My entry point (`index.tsx`) changes are pushed straight out to connected clients
* Imported modules (eg: `HelloWorld.tsx`) is displayed on first load but changes are not shown

So lrload is only showing me live updates on my root most file, not on any others. I know the change happens and it works as I'm seeing output in my terminal and my dev tools console, just nothing happens visually.

I've got the code here - https://github.com/aaronpowell/react-typescript-workshop/tree/ab3f9f3c09fafe77cc2a2dc70a1ee64a44ecdfd4 and would appreciate any tips on what I'm missing.

**Comment by milankinen** [comment]
Aah, you are using `fullPaths: true` in your browserify config which breaks the reload propagation logic. If you set `fullPath: false` in your `gulpfile.js` then the reloading starts to work (however it always overrides the state of your components because we have issues with babel 6.x, see #77 and #78).

This is definitely a bug, I created a dedicated bug issue for this one: #80

**Comment by aaronpowell** [comment]
Sweet, that sorted it out :smile: 

I can live with the full paths being disabled.
