### ISSUE TITLE
Not reloading?

### ISSUE THREAD

**Issue by mattdesl** [milankinen/livereactload#9]
Awesome stuff here. :+1: 

I'm trying to use [http-server](https://github.com/indexzero/http-server) instead of express to serve some static `index.html`. For some reason this is not causing it to reload. I'm testing in the gulp example -- everything works fine with express.

Added my own `index.html`, removed server stuff from gulpfile, and used this command: `http-server . -p 3000`.

I am getting `new client connected` and `sending reload request to 1 clients` but no hot-reloads. Page renders fine and changes on hard refresh as expected.

Any ideas?

**Comment by mattdesl** [comment]
OK - seems like I need to re-start the HTTP server on file change. Is there any way around that?

**Comment by milankinen** [comment]
Yes. This might happen when your server sends the cache headers and you have not disabled caches from you browser (reloading client tries to reload the same script but gets the cached one instead of).

I created more general issue (https://github.com/milankinen/livereactload/issues/12) and close this one.
