### ISSUE TITLE
Versions to install

### ISSUE THREAD

**Issue by mattdesl** [milankinen/livereactload#91]
I'm just setting up with the readme – it's suggesting I install react-proxy@1.x and a beta version of the babel-plugin react transform. Any reason why we can't just install the latest?

**Comment by milankinen** [comment]
Actually it seems that `babel-plugin-react-transformation` has moved from beta stage to live so I should update docs a little bit.

About `react-proxy@1.x`, only `1.x` version is supported, because version 2 has some breaking changed that need to be solved first (other HMR solutions have [the same issue](https://github.com/gaearon/react-transform-hmr/blob/master/package.json#L36)). Please see #72
